Backend/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\UserController;
use App\Http\Controllers\PortfolioController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\ConnexionController;
use App\Http\Controllers\Admin\ArticlesController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('posts', PostController::class);

Route::resource('users', UserController::class);

Route::resource('connexions', ConnexionController::class);
Route::get('/articles',                               'Admin\ArticlesController@index');

Route::get('/admin/articles',                               'Admin\ArticlesController@index');
Route::get('/admin/articles/create',                        'Admin\ArticlesController@create');
Route::post('/admin/articles',                              'Admin\ArticlesController@store');
Route::get('/admin/articles/{article}/edit',                'Admin\ArticlesController@edit')->name('admin/articles/edit');
Route::post('/admin/articles/{article}',                    'Admin\ArticlesController@update')->name('admin/articles/update');
Route::delete('/admin/articles/{article}',                  'Admin\ArticlesController@destroy')->name('admin/articles/destroy');


Route::get('/admin/articles-with-relationships',            'Admin\ArticlesWithRelationshipController@index');
Route::get('/admin/articles-with-relationships/create',     'Admin\ArticlesWithRelationshipController@create');
Route::post('/admin/articles-with-relationships',           'Admin\ArticlesWithRelationshipController@store');
Route::get('/admin/articles-with-relationships/{articlesWithRelationship}/edit','Admin\ArticlesWithRelationshipController@edit')->name('admin/articles-with-relationships/edit');
Route::post('/admin/articles-with-relationships/{articlesWithRelationship}','Admin\ArticlesWithRelationshipController@update')->name('admin/articles-with-relationships/update');
Route::delete('/admin/articles-with-relationships/{articlesWithRelationship}','Admin\ArticlesWithRelationshipController@destroy')->name('admin/articles-with-relationships/destroy');

Route::get('/admin/articles',                               'Admin\ArticlesController@index');
Route::get('/admin/articles/create',                        'Admin\ArticlesController@create');
Route::post('/admin/articles',                              'Admin\ArticlesController@store');
Route::get('/admin/articles/{article}/edit',                'Admin\ArticlesController@edit')->name('admin/articles/edit');
Route::post('/admin/articles/bulk-destroy',                 'Admin\ArticlesController@bulkDestroy')->name('admin/articles/bulk-destroy');
Route::post('/admin/articles/{article}',                    'Admin\ArticlesController@update')->name('admin/articles/update');
Route::delete('/admin/articles/{article}',                  'Admin\ArticlesController@destroy')->name('admin/articles/destroy');

Backend/app/Models/Connexion.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;



class Connexion extends Model
{
    use HasFactory;

    protected $fillable = [
        'TYPE_HEBERGEMENT', 'PROMISE_CASE', 'STATUS', 'name','domain','port','username','password','remember_token'
    ];




    /**
    * Get the user's full name.
    *
    * @return string
    */
    public function getLink()
    {
        return "{$this->name}.{$this->domain}:{$this->port}";
    }

    public function connexions()
{
    $connexions = Connexion::get();

    foreach ($connexions as $key => $value) {
         echo $value->getLink;
    }
}

}

Backend/app/Http/Controllers/ConnexionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Connexion;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ConnexionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Connexion::latest()->paginate(5);
    
        return view('connexions.index',compact('data'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('connexions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'TYPE_HEBERGEMENT' => 'required',
            'PROMISE_CASE' => 'required',
           
        ]);

        //$request->getLink([
        //    'link' => 'name'+'domain'+":"+'port'
        //])


    
        Connexion::create($request->all());
     
        return redirect()->route('connexions.index')
                        ->with('success','Connexion created successfully.');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Connexion  $connexion
     * @return \Illuminate\Http\Response
     */
    public function show(Connexion $connexion)
    {
        return view('connexions.show',compact('connexion'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Connexion  $connexion
     * @return \Illuminate\Http\Response
     */
    public function edit(Connexion $connexion)
    {
        return view('connexions.edit',compact('connexion'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Connexion  $connexion
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Connexion $connexion)
    {
        $request->validate([
            'title' => 'required',
            'description' => 'required',
        ]);
    
        $connexion->update($request->all());
    
        return redirect()->route('connexions.index')
                        ->with('success','Connexion updated successfully');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Connexion  $connexion
     * @return \Illuminate\Http\Response
     */
    public function destroy(Connexion $connexion)
    {
        $connexion->delete();
    
        return redirect()->route('connexions.index')
                        ->with('success','connexion deleted successfully');

    }
}

Backend/resources/views/Connexions/create.blade.php
@extends('connexions.layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Connexion</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('connexions.index') }}"> Back</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('connexions.store') }}" method="POST">
    @csrf
  

     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>name</strong>
                <input type="text" name="name" class="form-control" placeholder="Enter name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>domain</strong>
                <input type="text" name="domain" class="form-control" placeholder="Enter name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>port</strong>
                <input type="text" name="port" class="form-control" placeholder="Enter name">
            </div>
        </div>
        <label for="TYPE_HEBERGEMENT">TYPE_HEBERGEMENT</label>
        <select class="form-select" name="TYPE_HEBERGEMENT">
          <option value="PROMISE">PROMISE</option>
          <option value="CLOUD">CLOUD</option>
        </select>

        <label for="PROMISE_CASE">PROMISE_CASE</label>
        <select class="form-select" name="PROMISE_CASE">
          <option value="SSH">SSH</option>
          <option value="VPN">VPN</option>
          <option value="IPSEC">IPSEC</option>
        </select>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>username</strong>
                <textarea class="form-control" style="height:150px" name="username" placeholder="Enter Description"></textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>password</strong>
                <textarea class="form-control" style="height:150px" name="password" placeholder="Enter Description"></textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>token</strong>
                <textarea class="form-control" style="height:150px" name="token" placeholder="Enter Description"></textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button class="reset">CLEAR ENTRY</button>
            <button onclick="document.getElementById('selectform').reset(); document.getElementById('from').value = null; return false;">
                CLEAR ENTRY
            </button>
    </div>
    </div>
   
</form>
@endsection

Backend/resources/views/Connexions/edit.blade.php
@extends('connexions.layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Edit Connexion</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('connexions.index') }}"> Back</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('connexions.store') }}" method="POST">
    @csrf
    @method('PUT')  

     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>name: </strong>
                <input type="text" value="{{ $connexion->name }}" name="name" class="form-control" placeholder="Enter name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>domain: </strong>
                <input type="text" value="{{ $connexion->domain }}" name="domain" class="form-control" placeholder="Enter name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>port: </strong>
                <input type="text" value="{{ $connexion->port }}" name="port" class="form-control" placeholder="Enter name">
            </div>
        </div>
        <label for="TYPE_HEBERGEMENT">TYPE_HEBERGEMENT</label>
        <select class="form-select" name="TYPE_HEBERGEMENT">
          <option value="PROMISE">PROMISE</option>
          <option value="CLOUD">CLOUD</option>
        </select>

        <label for="PROMISE_CASE">PROMISE_CASE</label>
        <select class="form-select" name="PROMISE_CASE">
          <option value="SSH">SSH</option>
          <option value="VPN">VPN</option>
          <option value="IPSEC">IPSEC</option>
        </select>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>username: </strong>
                <textarea class="form-control" value="{{ $connexion->username }}" style="height:150px" name="username" placeholder="Enter Description"></textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>password: </strong>
                <textarea class="form-control" value="{{ $connexion->password }}" style="height:150px" name="password" placeholder="Enter Description"></textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>token: </strong>
                <textarea class="form-control" value="{{ $connexion->token }}" style="height:150px" name="token" placeholder="Enter Description"></textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button class="reset">CLEAR ENTRY</button>
            <button onclick="document.getElementById('selectform').reset(); document.getElementById('from').value = null; return false;">
                CLEAR ENTRY
            </button>
    </div>
    </div>
   
</form>
@endsection

Backend/resources/views/Connexions/index.blade.php
@extends('connexions.layout')
 
@section('content')


    <div class="row" style="margin-top: 5rem;">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Gestionnaire de Connexion</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('connexions.create') }}"> Create New Connexion</a>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>hebergement</th>
            <th>promise</th>
            <th>name</th>
            <th>domain</th>
            <th>port</th>
            <th>link</th>
            <th>username</th>
            <th>password</th>
            <th>Token</th>
            <th>Status</th>
            <th>createdAt</th>
            <th>uploadedAt</th>
            <th>deletedAt</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($data as $key => $value)
        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $value->TYPE_HEBERGEMENT }}</td>
            <td>{{ $value->PROMISE_CASE }}</td>
            
            <td>{{ $value->name }}</td>
            
            <td>{{ $value->domain }}</td>
            <td>{{ $value->port }}</td>
            <td>{{ $value->link }}</td>
            <td>{{ $value->username }}</td>
            <td>{{ $value->password }}</td>
            <td>{{ $value->remember_token }}</td>
            <td>{{ $value->STATUS }}</td>
            <td>{{ $value->created_at }}</td>
            <td>{{ $value->updated_at }}</td>
            <td>{{ $value->deleted_at }}</td>
            
            <td>
            </td>
        </tr>
        @endforeach
    </table>  
    {!! $data->links() !!}      
@endsection

Backend/resources/views/Connexions/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Gestionnaire de Connexion</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>
<body>
  
<div class="container">
    @yield('content')
</div>
   
</body>
</html>

Backend/resources/views/Connexions/show.blade.php
@extends('connexions.layout')
  
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Connexion</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('connexions.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>name:</strong>
                {{ $connexion->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>domain:</strong>
                {{ $connexion->domain }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>port:</strong>
                {{ $connexion->port }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>TYPE_HEBERGEMENT: </strong>
                {{ $connexion->TYPE_HEBERGEMENT }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>PROMISE_CASE:</strong>
                {{ $connexion->PROMISE_CASE }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>username:</strong>
                {{ $connexion->username }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>password:</strong>
                {{ $connexion->password }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>token:</strong>
                {{ $connexion->token }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>createdAt:</strong>
                {{ $connexion->created_at }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>updated_at:</strong>
                {{ $connexion->updated_at }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>deleted_at:</strong>
                {{ $connexion->deleted_at }}
            </div>
        </div>
        
    </div>
@endsection